# Las credenciales SSH se configuran en AWX, no en este inventario.

[ubuntu:children]
containers
vms

[containers:children]
dns
wireguard
loadbalancer
unifi

[vms:children]
ibk

[dns]
dns01.pro.perelohome.com ansible_host=10.10.2.14
dns02.pro.perelohome.com ansible_host=10.10.2.15

[wireguard]
wireguard-01.pro.perelohome.com ansible_host=10.10.2.16
wireguard-02.pro.perelohome.com ansible_host=10.10.2.17

[loadbalancer]
lb-01.okd.pro.perelohome.com ansible_host=10.10.20.6
lb-02.okd.pro.perelohome.com ansible_host=10.10.20.7

[unifi]
unifi-controller.perelohome.com ansible_host=192.168.1.23

[ibk]
ibk.perelohome.com ansible_host=10.10.2.19
